### ISSUE TITLE
add DissService properties

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-schema#1]
https://vocabs.acdh.oeaw.ac.at/schema#hasDissService

**Comment by bellerophons-pegasus** [comment]
Will only Resources have a Dissemination Service? Or do you already know or can think of a case where also Collections might have one?

**Comment by ctot-nondef** [comment]
The collection download for example, if I understand it correctly it's also a dissemination service and applies to collections

**Comment by bellerophons-pegasus** [comment]
Yes, but the download is added in a different way, as our documentation (yay, we have some) says: https://redmine.acdh.oeaw.ac.at/projects/acdh-repo/wiki/Dissemination_Services 

hasDissService is intended as something when it is a very special and dedicated service, which probably will only be used once

**Comment by csae8092** [comment]
currently hasDissService is only used for acdh:Resources but since we can't really anticipate what we might will be able to do for some specific collections, I'd be generous and set domain for acdh:hasDissService to collection as well
and as far as `collection download` is concerned, this is simply linked to all fedora:Resource instances
