### ISSUE TITLE
hasNonLinkedIdentifier for all classes

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-schema#17]
currently `hasNonLinkedIdentifier` is restricted to p,c,r,m,pub which makes it impossible to save project specific IDs for entities like person, places or institutions although a lot of projects do carefully curate IDs for their entities. Information which for now can't be preserved properly on ARCHE-MD level

**Comment by carlonim** [comment]
Just changed domain of `hasNonLinkedIdentifier` to `Main`: #19 
As soon as approval is given, I'll merge to the master branch.
