### ISSUE TITLE
Rename acdh:hasService to acdh:hasDisseminationService

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-schema#5]
The ontology includes the technical property acdh:hasService to link a resource with a dissemination service. I think it would be better to rename it to acdh:hasDisseminationService. Although it is longer, it is more precise and does not leave too much room for speculation about what service is meant. 

@zozlak what do you think?

**Comment by zozlak** [comment]
I have nothing against renaming it.

Personally I don't like this property at all (as it's values are difficult to maintain - I mean when someone changes dissemination service definitions, (s)he for sure doesn't remember to check if/how it affects existing acdh:hasService triples).

Fortunately we don't have any triple like that both on apollo and minerva. Which makes me thinking of removing this property from the ontology.

What do you think @bellerophons-pegasus ? @csae8092 - any objections?

**Comment by bellerophons-pegasus** [comment]
Oh if you ask me I would also vote for removing it, as I would like to encourage setting up proper rules for dissemination services

**Comment by csae8092** [comment]
remove it

**Comment by bellerophons-pegasus** [comment]
done :-)
