### ISSUE TITLE
Metadata cleanup for V2.0

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-schema#6]
[Reference list of all issues](https://github.com/acdh-oeaw/arche-schema/pull/3#issuecomment-775360599)

I am not firm in SQL. Thus here a list of actions for some of the items listed in https://github.com/acdh-oeaw/arche-schema/pull/3#issuecomment-775360599

* Property https://vocabs.acdh.oeaw.ac.at/schema#isPartOf with domain https://vocabs.acdh.oeaw.ac.at/schema#PlaceOrPublicationOrRepoObject is used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter 6
  * -> exchange https://vocabs.acdh.oeaw.ac.at/schema#isPartOf with https://vocabs.acdh.oeaw.ac.at/schema#relation (If I understood you right you changed that anyway?)
* Property https://vocabs.acdh.oeaw.ac.at/schema#hasDepositor with domain https://vocabs.acdh.oeaw.ac.at/schema#RepoObject is used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#Project 1
  * -> remove https://vocabs.acdh.oeaw.ac.at/schema#hasDepositor from that project 

* Resource 30304 
  * too many values (2) for property https://vocabs.acdh.oeaw.ac.at/schema#hasFormat and lang
  * -> keep "audio/x-wav"
* Resource 35808
  * too many values (4) for property https://vocabs.acdh.oeaw.ac.at/schema#hasExtent and lang en
  * -> should be "100910000000 tokens, 40159000 documents, 305580000 paragraphs, 667000000 sentences"@en (merge all four values into one, separated by ', '
  * -> Same applies to `acdh:hasExtent` for Resources 3619, 36918, 36543 and 38513 (all contain "AMC Austrian Media Corpus" in `acdh:hasTitle`)
* Resource 36543
  * too many values (2) for property https://vocabs.acdh.oeaw.ac.at/schema#hasFormat and lang
  * -> keep "text/xml"

More will follow on Monday

**Comment by zozlak** [comment]
> Property https://vocabs.acdh.oeaw.ac.at/schema#isPartOf used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter

Yes, this is done already, e.g. https://github.com/acdh-oeaw/arche-docker-config/blob/arche/initScripts/dissServices.ttl#L47

**Comment by zozlak** [comment]
> remove https://vocabs.acdh.oeaw.ac.at/schema#hasDepositor from that project
Done

**Comment by zozlak** [comment]
So far everything cleaned up, please reopen when new orders come.

**Comment by bellerophons-pegasus** [comment]
For the entities in ARCHE that have rdf:type = https://vocabs.acdh.oeaw.ac.at/schema#Collection and rdf:type = https://vocabs.acdh.oeaw.ac.at/schema#TopCollection the first (Collection) should be removed. Otherwise the biblatex dissemination service won't work properly.

**Comment by zozlak** [comment]
Just for that we need to deploy GUI adjusted to make use of `acdh:TopCollection`.
As it's already the case on minerva, I dropped `acdh:Collection` from top collections there but I'm afraid it's still not the case on apollo.

**Comment by bellerophons-pegasus** [comment]
It seems the GUI is also halfway updated on Apollo. E.g. https://arche.acdh.oeaw.ac.at/browser/oeaw_detail/105578 shows up in the root view and only has `acdh:hasTopCollection` assigned to it.
(I'm a bit confused about the versions in use on our instances)

**Comment by zozlak** [comment]
Fixed on apollo as well after Norbert confirmed GUI on apollo can deal with TopCollections

**Comment by bellerophons-pegasus** [comment]
A few more bulk tasks:

* Property https://vocabs.acdh.oeaw.ac.at/schema#hasLifeCycleStatus with domain https://vocabs.acdh.oeaw.ac.at/schema#Container is used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#Resource 1739
  * -> can be removed from these Resources without any replacement


* Property https://vocabs.acdh.oeaw.ac.at/schema#hasCompleteness with domain https://vocabs.acdh.oeaw.ac.at/schema#Collection is used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#Resource 1730
   * -> can be safely removed for those Resources where the value is 'The resource is finished and the file is final.'

* Property https://vocabs.acdh.oeaw.ac.at/schema#hasHosting with domain https://vocabs.acdh.oeaw.ac.at/schema#RepoObject is used in incompatible classes: https://vocabs.acdh.oeaw.ac.at/schema#Publication 59 and https://vocabs.acdh.oeaw.ac.at/schema#Project 1
   * ->  can be removed from these Resources without any replacement

**Comment by zozlak** [comment]
Applied

**Comment by zozlak** [comment]
> Property https://vocabs.acdh.oeaw.ac.at/schema#isMetadataFor with domain https://vocabs.acdh.oeaw.ac.at/schema#Metadata is used in resources of incompatible classes:
> * https://vocabs.acdh.oeaw.ac.at/schema#Resource 4 (39632, 39825, 40033, 48503)

These are all CMDI records for AMC with a wrong class attached. Changing their class to https://vocabs.acdh.oeaw.ac.at/schema#Metadata

**Comment by bellerophons-pegasus** [comment]
I think we can close this, can we?
