### ISSUE TITLE
acdh:hasLiteralIdentifier has two ranges

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-schema#7]
https://github.com/acdh-oeaw/arche-schema/blob/master/acdh-schema.owl#L1781-L1782

It should probably be only `http://www.w3.org/2001/XMLSchema#anyURI`

**Comment by bellerophons-pegasus** [comment]
`acdh:hasLiteralIdentifier` is a property that groups together `acdh:hasMetadataPid` (any URI), `acdh:hasPid` (anyURI), `acdh:hasTemporalCoverageIdentifier` (anyURI) and `acdh:hasNonLinkedIdentifier` (string), Thus the range is anyURI or string.

**Comment by zozlak** [comment]
I guess it's not a correct way of stating that. Especially does owl say we should interpret it as "any of listed ranges" and not as "all of listed ranges"? If I remember correctly there are specific constructs to deal with this ambiguity in owl and I would expect that it would end up with an additional anonymous datatype "xsd:anyURL or xxsd:string" (just like it works for classes). Anyway as this property only creates a hierarchy and is not meant to be actually used, we don't have to check all the concerns I raised.

**Comment by bellerophons-pegasus** [comment]
Ha, yes ... a union. I can correct that, so that it is at least formally correct for one of our next versions
