### ISSUE TITLE
acdh:hasLiteralIdentifier lacks acdh:ordering annotation property

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-schema#8]

**Comment by bellerophons-pegasus** [comment]
This is on purpose. Not all of our properties have the ordering annotation, because they should not be displayed in the metadata editor

**Comment by zozlak** [comment]
Ah, fine. But if that's so, you probably also don't want it in the [root table](https://arche-dev.acdh-dev.oeaw.ac.at/browser/api/getRootTable/en?_format=html). A rule for Norbert can probably be "skip properties reporting order 99999" (the arche-lib-schema sets order to arbitrary chosen high number - 99999 - when it's not provided so such properties don't get listed first).

**Comment by bellerophons-pegasus** [comment]
The root table should display everything. So it is fine as it currently is.
